"""empty message

Revision ID: 357d019c4741
Revises: b25af5566caa
Create Date: 2024-11-20 16:23:32.278840

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "357d019c4741"
down_revision: Union[str, None] = "b25af5566caa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

table_name = "User"
attempts_column = "login_attempts"
mode_column = "login_mode"
cooldown_column = "login_cooldown_end"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        table_name,
        sa.Column(
            cooldown_column,
            sa.TIMESTAMP(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
    )
    op.add_column(
        table_name,
        sa.Column(attempts_column, sa.Integer(), nullable=True)
    )
    op.add_column(
        table_name,
        sa.Column(mode_column, sa.String(length=8), nullable=True)
    )

    op.execute(
        f"""UPDATE "{table_name}" SET {attempts_column} = 0
        WHERE {attempts_column} IS NULL"""
    )
    op.alter_column(table_name, attempts_column, nullable=False)
    op.execute(
        f"""UPDATE "{table_name}" SET {mode_column} = 'active'
        WHERE {mode_column} IS NULL"""
    )
    op.alter_column(table_name, mode_column, nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(table_name, mode_column)
    op.drop_column(table_name, attempts_column)
    op.drop_column(table_name, cooldown_column)
    # ### end Alembic commands ###
