"""empty message

Revision ID: 5e2c789250ae
Revises: b25af5566caa
Create Date: 2024-11-19 00:34:55.901810

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "5e2c789250ae"
down_revision: Union[str, None] = "b25af5566caa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

table_name = "User"
attempts_column = "login_attempts"
status_column = "login_status"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "User",
        sa.Column(
            "login_attempts",
            sa.Integer(),
            nullable=True,
        )
    )
    op.add_column(
        "User",
        sa.Column(
            "login_status",
            sa.String(length=8),
            nullable=True,
        )
    )

    op.execute(
        f"""UPDATE "{table_name}" SET {attempts_column} = 0
        WHERE {attempts_column} IS NULL"""
    )
    op.alter_column(table_name, attempts_column, nullable=False)
    op.execute(
        f"""UPDATE "{table_name}" SET {status_column} = 'active'
        WHERE {status_column} IS NULL"""
    )
    op.alter_column(table_name, status_column, nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "login_status")
    op.drop_column("User", "login_attempts")
    # ### end Alembic commands ###
